name: OPT
dependencies:
  - blas=1.0
  - ca-certificates=2020.6.24
  - certifi=2020.6.20
  - cloudpickle=1.5.0
  - cycler=0.10.0
  - cytoolz=0.10.1
  - dask-core=2.22.0
  - dbus=1.13.6
  - decorator=4.4.2
  - expat=2.2.6
  - fontconfig=2.13.0
  - freetype=2.9.1
  - glib=2.56.2
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - imageio=2.9.0
  - intel-openmp=2019.3
  - jpeg=9b
  - kiwisolver=1.1.0
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libpng=1.6.37
  - libtiff=4.0.10
  - libuuid=1.0.3
  - libxml2=2.9.9
  - matplotlib=3.1.0
  - mkl=2019.3
  - mkl_fft=1.0.12
  - mkl_random=1.0.2
  - ncurses=6.1
  - networkx=2.4
  - numpy=1.16.3
  - numpy-base=1.16.3
  - olefile=0.46
  - openssl=1.1.1g
  - pandas=0.24.2
  - pcre=8.43
  - pillow=6.0.0
  - pip=19.1.1
  - pyparsing=2.4.0
  - pyqt=5.9.2
  - python=3.6.8
  - python-dateutil=2.8.0
  - pytz=2019.1
  - pywavelets=1.1.1
  - pyyaml=5.3.1
  - qt=5.9.7
  - readline=7.0
  - scikit-image=0.16.2
  - scipy=1.2.1
  - setuptools=41.0.1
  - sip=4.19.8
  - six=1.12.0
  - sqlite=3.28.0
  - tk=8.6.8
  - toolz=0.10.0
  - tornado=6.0.2
  - wheel=0.33.4
  - xz=5.2.4
  - yaml=0.2.5
  - zlib=1.2.11
  - zstd=1.3.7

